### ISSUE TITLE
Recovering stake from multiple operators - disappearing "recover" button

### ISSUE THREAD

**Issue by pdyraga** [keep-network/keep-core#2070] opened 2020-09-21 08:59 UTC
It's a report from one of the early KEEP stakers.

In April (staking contract v1), our staker delegated to three operators and later undelegated from all of them. After recovering the stake from the first operator, buttons for recovering the stake from the rest of the operators disappeared. It has been confirmed that it still does not work with the most recent KEEP Token Dashboard.

**Comment by r-czajkowski** [comment] 2020-09-22 10:23
I was not able to reproduce it locally via Metamask. I delegated tokens from liquid tokens, grant and managed grant.

Going to test this scenario with Ledger and Trezor wallet. I'll post result soon.

**Comment by pdyraga** [comment] 2020-09-22 10:25
If that helps, the transactions are:

original delegation 1 https://etherscan.io/tx/0x141f4e29d495cdbba98f47552aa93558672219d7827c71dde42640d1934f36c1
original delegation 2 https://etherscan.io/tx/0xa73ede0270ca8cadec0fe968e482723c19891837f4f16e31e983ca39bc783c45
original delegation 3 https://etherscan.io/tx/0x3c957ee392129e94bee588bd8435d173f325a1afab6e0035edbb53e59c9aba08

recovery (original delegation3) https://etherscan.io/tx/0xb75f79e09c9ef153902df5ff71d330a2ac503780db501b1ff66f6bde2dd20c6d

**Comment by r-czajkowski** [comment] 2020-09-22 10:44
> It has been confirmed that it still does not work with the most recent KEEP Token Dashboard.

Are we sure that this account delgated tokens against the new `TokenStaking` contract? We should remember about the token dashboard only displays data from the new `TokenStaking` contract.

**Comment by r-czajkowski** [comment] 2020-09-22 10:45
I tested scenario with Ledger and the result is the same as [here](https://github.com/keep-network/keep-core/issues/2070#issuecomment-696635034).

**Comment by pdyraga** [comment] 2020-09-22 11:47
We could always recommend to call `recoverStake` on the old `TokenStaking` directly and pass operator contract there.
https://etherscan.io/address/0x6D1140a8c8e6Fac242652F0a5A8171b898c67600

Anyone can call this function for any operator.

Less than ideal, but it's a much faster solution than fixing bug in the old dashboard and deploying it.

**Comment by r-czajkowski** [comment] 2020-09-22 12:24
I've hacked a dapp and I'm able to see these 2 delegations againts "old" `TokenStaking` contract after clicking on the update banner.

![obraz](https://user-images.githubusercontent.com/57687279/93881403-2496f180-fcdf-11ea-8d04-7cd158841113.png)

**Comment by r-czajkowski** [comment] 2020-09-22 12:26
Also the user can `recoverStake` from "old" `TokenStaking` via dapp if selects the `undelegate` path through the copy stake flow.

**Comment by r-czajkowski** [comment] 2021-05-25 10:31
I think we can close this issue because we are not able to recreate the described scenario.

**Closed by r-czajkowski** 2021-05-25 10:31 UTC
Labels: :old_key: token dashboard
