### ISSUE TITLE
Clicking to address "copy to clipboard" don't work

### ISSUE THREAD

**Issue by k0kk0k** [keep-network/keep-core#1776] opened 2020-05-08 18:57 UTC
OS: Windows 10 v1909
Browser: Google Chrome v81.0.4044.138
![demo](https://user-images.githubusercontent.com/60854664/81438631-c0cbbc00-9175-11ea-92fb-7f2dca8f8e4f.gif)

**Comment by r-czajkowski** [comment] 2020-05-25 10:54
Duplicate of: #1771

Thanks for reporting! I hope this problem has been addressed with #1791.

**Closed by r-czajkowski** 2020-05-25 10:54 UTC
